export const calendarClassNames = {
    root: 'w-full',
    months: 'w-full',
    month: 'w-full',
    month_caption: 'relative flex items-center justify-center py-2',
    caption_label: 'text-sm font-semibold text-gray-900',
    nav: 'absolute inset-x-0 top-2 flex items-center justify-between',
    button_previous: 'h-8 w-8 rounded-full border border-gray-200 bg-white text-gray-500 hover:text-gray-900 hover:border-gray-300',
    button_next: 'h-8 w-8 rounded-full border border-gray-200 bg-white text-gray-500 hover:text-gray-900 hover:border-gray-300',
    chevron: 'h-4 w-4 fill-current',
    month_grid: 'w-full border-separate border-spacing-1',
    weekdays: '',
    weekday: 'text-center text-[11px] font-semibold text-gray-400 uppercase py-1',
    weeks: '',
    week: '',
    day: 'text-center',
    day_button: 'mx-auto flex h-9 w-9 items-center justify-center rounded-lg text-sm font-medium text-gray-700 transition-colors hover:bg-primary/10',
    today: 'border border-primary text-primary',
    selected: 'bg-red-500 text-white shadow-sm',
    range_start: 'bg-red-500 text-white shadow-sm',
    range_end: 'bg-red-500 text-white shadow-sm',
    range_middle: 'bg-emerald-100 text-emerald-700',
    outside: 'text-gray-300',
    disabled: 'text-gray-300 opacity-50',
};
